[build-system]
requires = ['setuptools', 'setuptools_scm', 'wheel']
build-backend = 'setuptools.build_meta'

[dev-dependencies]
black = { version = "^19.10", python = "^3.6" }
pytest = { version = "^5.3", python = "^3.6" }

[tool.black]
line-length = 88
target_version = ['py36']
